---
# Configure base system environment
- name: Install base system packages
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - curl
      - wget
      - unzip
    state: present
    update_cache: yes
  become: yes
  tags:
    - base-system

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  become: no
  tags:
    - base-system
    - zsh

- name: Set Zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
  tags:
    - base-system
    - zsh

- name: Prompt for Oh My Zsh plugins
  ansible.builtin.pause:
    prompt: "Install Oh My Zsh plugins (syntax highlighting, autocompletion) (y/n)?"
    seconds: 300
  register: zsh_plugins_choice
  until: zsh_plugins_choice.user_input | lower in ['y', 'n']
  retries: 3
  become: no
  tags:
    - base-system
    - zsh
- name: Set fact for Zsh plugins
  ansible.builtin.set_fact:
    install_zsh_plugins: "{{ 'true' if zsh_plugins_choice.user_input | lower == 'y' else 'false' }}"
  tags:
    - base-system
    - zsh

- name: Install Oh My Zsh plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    version: master
  loop:
    - { name: 'zsh-syntax-highlighting', repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git' }
    - { name: 'zsh-autosuggestions', repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' }
  when: install_zsh_plugins | bool
  become: no
  tags:
    - base-system
    - zsh

- name: Copy dynamic .zshrc template
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'
  become: no
  tags:
    - base-system
    - zsh
