---
- name: Check if Go is already installed
  command: go version
  register: go_version_check
  failed_when: false
  changed_when: false

- name: Download Go tarball
  get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: '0644'
  when: go_version_check.rc != 0

- name: Extract Go tarball
  unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes
  when: go_version_check.rc != 0

- name: Set Go environment variables
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    create: yes
  loop:
    - 'export GOROOT=/usr/local/go'
    - 'export GOPATH=$HOME/go'
    - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'
  when: go_version_check.rc != 0

- name: Create Go workspace directory
  file:
    path: "{{ ansible_env.HOME }}/go"
    state: directory
    mode: '0755'
  when: go_version_check.rc != 0

- name: Verify Go installation
  command: go version
  register: go_verify
  changed_when: false