---
# Install OpenJDK
- name: Install OpenJDK
  ansible.builtin.apt:
    name: "openjdk-{{ java_version | default('17') }}-jdk"
    state: present
    update_cache: yes
  become: true
  tags:
    - programming
    - java

- name: Set JAVA_HOME environment variable
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "export JAVA_HOME=/usr/lib/jvm/java-{{ java_version | default('17') }}-openjdk-amd64"
    create: yes
    mode: '0644'
  become: false
  tags:
    - programming
    - java