---
- name: Install OpenJDK
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
    update_cache: yes

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64'
    create: yes

- name: Verify Java installation
  command: java -version
  register: java_verify
  changed_when: false