---
# Install Node.js using NVM
- name: Check if NVM is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_check
  tags:
    - programming
    - nodejs

- name: Download and install NVM
  ansible.builtin.shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version | default('0.39.7') }}/install.sh | bash
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  become: false
  when: not nvm_check.stat.exists
  tags:
    - programming
    - nodejs

- name: Add NVM to PATH in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
  become: false
  when: not nvm_check.stat.exists
  tags:
    - programming
    - nodejs

- name: Install Node.js using NVM
  ansible.builtin.shell:
    cmd: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ nodejs_version | default('18.18.0') }} && nvm use {{ nodejs_version | default('18.18.0') }}
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ nodejs_version | default('18.18.0') }}"
  become: false
  tags:
    - programming
    - nodejs