---
# Install Argo CD CLI
- name: Download Argo CD CLI
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_version | default('2.9.0') }}/argocd-linux-{{ ansible_architecture | regex_replace('x86_64', 'amd64') }}"
    dest: /usr/local/bin/argocd
    mode: '0755'
  become: true
  tags:
    - devops
    - argocd-cli