# roles/devops_cloud_native/tasks/helm.yml
---
- name: Ensure dependencies for Helm are installed
  ansible.builtin.apt:
    name:
      - curl
      - gpg
    state: present
    update_cache: yes
  tags:
    - helm

- name: Add official Helm GPG key
  ansible.builtin.shell: |
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/helm.gpg
  tags:
    - helm

- name: Add Helm apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    update_cache: yes
    filename: helm
  tags:
    - helm

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
  tags:
    - helm