---
# Install Helm
- name: Download Helm
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version | default('3.12.0') }}-linux-{{ ansible_architecture | regex_replace('x86_64', 'amd64') }}.tar.gz"
    dest: "/tmp/helm-v{{ helm_version | default('3.12.0') }}.tar.gz"
    mode: '0644'
  become: true
  tags:
    - devops
    - helm

- name: Extract Helm
  ansible.builtin.unarchive:
    src: "/tmp/helm-v{{ helm_version | default('3.12.0') }}.tar.gz"
    dest: /tmp
    remote_src: yes
  become: true
  tags:
    - devops
    - helm

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/linux-{{ ansible_architecture | regex_replace('x86_64', 'amd64') }}/helm"
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes
  become: true
  tags:
    - devops
    - helm