---
# Install Jenkins CLI (requires Java from programming_languages)
- name: Ensure Java is installed
  ansible.builtin.apt:
    name: "openjdk-{{ java_version | default('17') }}-jdk"
    state: present
  become: true
  tags:
    - devops
    - jenkins-cli

- name: Download Jenkins CLI
  ansible.builtin.get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: "{{ ansible_env.HOME }}/.jenkins/jenkins-cli.jar"
    mode: '0644'
    validate_certs: no  # Localhost may not have valid cert
  become: false
  tags:
    - devops
    - jenkins-cli
  ignore_errors: true  # Jenkins server may not be running locally