# roles/devops_cloud_native/tasks/k3s_cli.yml
---
- name: Download K3s installer script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  tags:
    - k3s-cli

- name: Run K3s installer with no install, just get binary
  ansible.builtin.shell: |
    INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_SKIP_ENABLE=true /tmp/k3s-install.sh
  args:
    executable: /bin/bash
    creates: /usr/local/bin/k3s
  tags:
    - k3s-cli

- name: Clean up K3s installer script
  ansible.builtin.file:
    path: /tmp/k3s-install.sh
    state: absent
  tags:
    - k3s-cli

- name: Display K3s client tools installation confirmation
  ansible.builtin.debug:
    msg: "K3s client tools have been installed. To use them, you will need to configure your KUBECONFIG."
  tags:
    - k3s-cli