---
# Install K3s client tools
- name: Download K3s installer
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  become: true
  when: install_k3s_cli | bool
  tags:
    - devops
    - k3s-cli

- name: Install K3s client tools
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh --version {{ k3s_version | default('1.28.2+k3s1') }} --client-only
    creates: /usr/local/bin/k3s
  become: true
  when: install_k3s_cli | bool
  tags:
    - devops
    - k3s-cli

- name: Verify K3s installation
  ansible.builtin.command: k3s --version
  register: k3s_version
  changed_when: false
  failed_when: k3s_version.rc != 0
  when: install_k3s_cli | bool
  tags:
    - devops
    - k3s-cli
    - verification
