---
# Install K9s
- name: Download K9s
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version | default('0.32.5') }}/k9s_Linux_{{ ansible_architecture | regex_replace('x86_64', 'amd64') }}.tar.gz"
    dest: "/tmp/k9s_v{{ k9s_version | default('0.32.5') }}.tar.gz"
    mode: '0644'
  become: true
  tags:
    - devops
    - k9s

- name: Extract K9s
  ansible.builtin.unarchive:
    src: "/tmp/k9s_v{{ k9s_version | default('0.32.5') }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/k9s
  become: true
  tags:
    - devops
    - k9s