---
# Install Ollama
- name: Download Ollama installer
  ansible.builtin.get_url:
    url: https://ollama.ai/install.sh
    dest: /tmp/ollama-install.sh
    mode: '0755'
    checksum: sha256:{{ lookup('url', 'https://ollama.ai/install.sh') | hash('sha256') }}
  become: true
  tags:
    - devops
    - ollama

- name: Install Ollama
  ansible.builtin.command:
    cmd: /tmp/ollama-install.sh
    creates: /usr/local/bin/ollama
  become: true
  tags:
    - devops
    - ollama