---
# Install common database clients
- name: Install PostgreSQL client
  ansible.builtin.apt:
    name: postgresql-client-{{ postgresql_version | default('14') }}
    state: present
    update_cache: yes
  become: true
  tags:
    - databases
    - db-clients
    - postgresql

# Placeholder for additional database clients (e.g., MySQL, Redis)
- name: Install MySQL client
  ansible.builtin.apt:
    name: mysql-client
    state: present
  become: true
  tags:
    - databases
    - db-clients
    - mysql

- name: Install Redis client
  ansible.builtin.apt:
    name: redis-tools
    state: present
  become: true
  tags:
    - databases
    - db-clients
    - redis