# roles/databases/tasks/main.yml
---
- name: Database Tools Installation
  ansible.builtin.debug:
    msg: "Starting installation tasks for database tools based on user choices."

- name: Include common database clients installation tasks
  ansible.builtin.include_tasks: db_clients.yml
  when: install_db_clients is defined and install_db_clients | bool
  tags:
    - databases
    - db-clients

# You could expand this role later to include full database servers
# for local development (e.g., PostgreSQL, MySQL server via apt/docker).
# Example (if you had an install_postgresql_server variable and a postgresql_server.yml):
# - name: Include PostgreSQL server installation tasks
#   ansible.builtin.include_tasks: postgresql_server.yml
#   when: install_postgresql_server is defined and install_postgresql_server | bool
#   tags:
#     - databases
#     - postgresql-server