---
# Install PostgreSQL server
- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql
  become: true
  tags:
    - databases
    - postgresql-server

- name: Add PostgreSQL GPG key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true
  tags:
    - databases
    - postgresql-server

- name: Install PostgreSQL server
  ansible.builtin.apt:
    name: postgresql-{{ postgresql_version | default('14') }}
    state: present
    update_cache: yes
  become: true
  tags:
    - databases
    - postgresql-server

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
  become: true
  tags:
    - databases
    - postgresql-server