---
# Install PostgreSQL client (redundant with db_clients.yml for modularity)
- name: Install PostgreSQL client
  ansible.builtin.apt:
    name: postgresql-client-{{ postgresql_version | default('14') }}
    state: present
    update_cache: yes
  become: true
  tags:
    - databases
    - postgresql