---
# Install Containerization tools (Docker)
- name: Containerization Tools Installation
  ansible.builtin.debug:
    msg: "Starting installation tasks for Containerization tools (Docker)."
  tags:
    - containerization

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ ansible_architecture | regex_replace('x86_64', 'amd64') }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  become: yes
  tags:
    - containerization
    - docker

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  tags:
    - containerization
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce={{ docker_version | default('24.0.5') }}-1~ubuntu.{{ ansible_distribution_version }}~{{ ansible_distribution_release }}
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes
  tags:
    - containerization
    - docker

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes
  tags:
    - containerization
    - docker

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false
  failed_when: docker_version.rc != 0
  tags:
    - containerization
    - verification
