---
# Install Hugging Face CLI
- name: Install Hugging Face CLI via pip
  ansible.builtin.pip:
    name: huggingface_hub[cli]
    executable: pip3
    state: present
  become: false
  tags:
    - ai-ml
    - huggingface-cli

- name: Ensure Hugging Face CLI is in PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
    mode: '0644'
  become: false
  tags:
    - ai-ml
    - huggingface-cli