# roles/ai-ml-datascience/tasks/huggingface_cli.yml
---
- name: Ensure Python 3 pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  tags:
    - huggingface-cli

- name: Install Hugging Face CLI using pip
  ansible.builtin.pip:
    name: huggingface_hub
    state: present
    executable: pip3
  tags:
    - huggingface-cli

- name: Display instructions for Hugging Face CLI login
  ansible.builtin.debug:
    msg: "Hugging Face CLI (huggingface_hub) has been installed. To use it, you may need to authenticate by running 'huggingface-cli login' and providing your Hugging Face token."
  tags:
    - huggingface-cli