---
# Install JupyterLab
- name: Install JupyterLab via pip
  ansible.builtin.pip:
    name: jupyterlab=={{ jupyterlab_version | default('4.0.0') }}
    executable: pip3
    state: present
  become: false
  tags:
    - ai-ml
    - jupyterlab

- name: Ensure JupyterLab is in PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
    mode: '0644'
  become: false
  tags:
    - ai-ml
    - jupyterlab