# roles/ai-ml-datascience/tasks/pytorch.yml
---
- name: Ensure Python 3 pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  tags:
    - pytorch

- name: Install PyTorch and Torchvision using pip
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
    state: present
    executable: pip3
  tags:
    - pytorch

- name: Display PyTorch installation confirmation
  ansible.builtin.debug:
    msg: "PyTorch has been installed for a CPU-only environment. If you require GPU support, please follow the official PyTorch installation instructions for your specific hardware."
  tags:
    - pytorch