---
# Install NVIDIA drivers and CUDA (if GPU available)
- name: Add NVIDIA driver repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free"
    state: present
  become: true
  when: gpu_available | bool
  tags:
    - ai-ml
    - pytorch
    - gpu

- name: Install NVIDIA drivers and CUDA toolkit
  ansible.builtin.apt:
    name:
      - nvidia-driver
      - nvidia-cuda-toolkit
    state: present
    update_cache: yes
  become: true
  when: gpu_available | bool
  tags:
    - ai-ml
    - pytorch
    - gpu

# Install PyTorch
- name: Install PyTorch (CPU or GPU version based on availability)
  ansible.builtin.pip:
    name: "{{ 'torch==' + pytorch_version | default('2.3.0') + '+cu121' if gpu_available else 'torch==' + pytorch_version | default('2.3.0') }}"
    executable: pip3
    state: present
  become: false
  tags:
    - ai-ml
    - pytorch