---
# Install NVIDIA drivers and CUDA (if GPU available, shared with PyTorch)
- name: Add NVIDIA driver repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free"
    state: present
  become: true
  when: gpu_available | bool
  tags:
    - ai-ml
    - tensorflow
    - gpu

- name: Install NVIDIA drivers and CUDA toolkit
  ansible.builtin.apt:
    name:
      - nvidia-driver
      - nvidia-cuda-toolkit
    state: present
    update_cache: yes
  become: true
  when: gpu_available | bool
  tags:
    - ai-ml
    - tensorflow
    - gpu

# Install TensorFlow
- name: Install TensorFlow (CPU or GPU version based on availability)
  ansible.builtin.pip:
    name: "{{ 'tensorflow==' + tensorflow_version | default('2.15.0') if gpu_available else 'tensorflow-cpu==' + tensorflow_version | default('2.15.0') }}"
    executable: pip3
    state: present
  become: false
  tags:
    - ai-ml
    - tensorflow