---
# Install TensorFlow (deep learning framework).
# Installs CPU or GPU version based on 'gpu_available' fact,
# and supports specific versions or the latest available.

- name: Determine desired TensorFlow version
  ansible.builtin.set_fact:
    _tensorflow_version: "{{ tensorflow_version | default('latest') }}"
  tags:
    - ai-ml
    - tensorflow

- name: Install TensorFlow (CPU or GPU version) for {{ ansible_user }}
  ansible.builtin.pip:
    # If _tensorflow_version is 'latest', state: latest handles it.
    # Otherwise, pin to the specific version.
    name: >
      {{ 'tensorflow' if _tensorflow_version == 'latest' and gpu_available | bool else 'tensorflow-cpu' if _tensorflow_version == 'latest' and not (gpu_available | bool) else 'tensorflow==' + _tensorflow_version if gpu_available | bool else 'tensorflow-cpu==' + _tensorflow_version }}
    executable: pip3
    state: present # Installs or upgrades to desired state/version
  become: true # Use sudo to ensure correct execution context
  become_user: "{{ ansible_user }}" # IMPORTANT: Execute pip installation as the target user (e.g., ubuntu)
  tags:
    - ai-ml
    - tensorflow