---
# Install AWS CLI
- name: Download AWS CLI installer
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture | regex_replace('x86_64', 'x86_64') | regex_replace('aarch64', 'aarch64') }}.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'
  become: true
  tags:
    - cloud-cli
    - aws-cli

- name: Extract AWS CLI
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes
  become: true
  tags:
    - cloud-cli
    - aws-cli

- name: Install AWS CLI
  ansible.builtin.command:
    cmd: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    creates: /usr/local/bin/aws
  become: true
  tags:
    - cloud-cli
    - aws-cli