---
# Install Google Cloud SDK (gcloud)
- name: Add Google Cloud SDK APT repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: google-cloud-sdk
  become: true
  tags:
    - cloud-cli
    - gcloud

- name: Add Google Cloud SDK GPG key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  become: true
  tags:
    - cloud-cli
    - gcloud

- name: Install Google Cloud SDK
  ansible.builtin.apt:
    name: google-cloud-sdk={{ gcloud_version | default('447.0.0-0') }}
    state: present
    update_cache: yes
  become: true
  tags:
    - cloud-cli
    - gcloud

- name: Ensure Google Cloud SDK is in PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="/usr/lib/google-cloud-sdk/bin:$PATH"'
    create: yes
    mode: '0644'
  become: false
  tags:
    - cloud-cli
    - gcloud