---
- name: Common Setup Tasks
  hosts: local
  become: yes
  tasks:
    - name: Ensure system is up-to-date
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      tags:
        - common