---
- name: Provision Developer Toolkit
  hosts: all
  become: yes
  roles:
    - prompt_user
    - base_system
    - programming_languages
    - devops-cloud
    - ai-ml-dataScience
    - databases
    - cloud-cli
    - ide_editors
    - version_control
    - containerization
    - cli_tools